# Generated by Django 3.0.8 on 2020-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
