# Generated by Django 3.0.8 on 2020-09-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_postpdf_ppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('guser', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='fPostpdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='filepdf/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.fpPost')),
            ],
        ),
    ]
