# Generated by Django 3.0.8 on 2020-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_fpostpdf_fppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puser', models.CharField(max_length=2000)),
                ('image', models.FileField(upload_to='files/')),
                ('like', models.CharField(max_length=2000)),
                ('dislike', models.CharField(max_length=2000)),
            ],
        ),
    ]
