# Generated by Django 3.0.8 on 2021-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
